# Generated by Django 2.0 on 2017-12-26 21:25

import coredrca.models
import coredrca.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Infarmed',
            fields=[
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('idFarmacia', models.ForeignKey(on_delete=coredrca.models.Farmacia, to='coredrca.Farmacia')),
                ('nome', models.ForeignKey(on_delete=coredrca.models.Infarmed, to='coredrca.Infarmed')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False, validators=[coredrca.validators.validate_domainonly_nome])),
                ('morada', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=15)),
                ('especialidade', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='MedReceita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('idMedico', models.ForeignKey(on_delete=coredrca.models.Medico, to='coredrca.Medico')),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('morada', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=15)),
                ('idMedico', models.ManyToManyField(to='coredrca.Medico')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='idUtente',
            field=models.ForeignKey(on_delete=coredrca.models.Utente, to='coredrca.Utente'),
        ),
        migrations.AddField(
            model_name='medreceita',
            name='idReceita',
            field=models.ForeignKey(on_delete=coredrca.models.Receita, to='coredrca.Receita'),
        ),
        migrations.AddField(
            model_name='medreceita',
            name='nome',
            field=models.ForeignKey(on_delete=coredrca.models.Infarmed, to='coredrca.Infarmed'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='idReceita',
            field=models.ManyToManyField(to='coredrca.Receita'),
        ),
    ]
