# Generated by Django 2.0 on 2017-12-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredrca', '0002_auto_20171227_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='idReceita',
            field=models.ManyToManyField(to='coredrca.Receita'),
        ),
    ]
